x-veld:
  chainput:
    # TODO
    about:
      description:
      topics:

services:
  veld:
    image: bash:5.2.21
    volumes:
      - ./veld_data_5_apis_oebl__ner_gold/data/:/veld/input/
      - ./APIS_OEBL__Named_Entity_Recognition/:/veld/output/
    command: cp /veld/input/apis_oebl__ner__3_cleaned_simplified.json /veld/output/data.json

